// <auto-generated />
namespace BontoBuy.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConflictRegister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConflictRegister));
        
        string IMigrationMetadata.Id
        {
            get { return "201602041420176_ConflictRegister"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
